src/Entity/Projectsemma.php
<?php

namespace App\Entity;

use App\Repository\ProjectsemmaRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProjectsemmaRepository::class)]
class Projectsemma
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $project_name = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(length: 255)]
    private ?string $used_technology = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProjectName(): ?string
    {
        return $this->project_name;
    }

    public function setProjectName(string $project_name): self
    {
        $this->project_name = $project_name;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getUsedTechnology(): ?string
    {
        return $this->used_technology;
    }

    public function setUsedTechnology(string $used_technology): self
    {
        $this->used_technology = $used_technology;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }
}

src/Form/ProjectsemmaType.php
<?php

namespace App\Form;

use App\Entity\Projectsemma;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProjectsemmaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add ('id')
            ->add('project_name')
            ->add('date')
            ->add('used_technology')
            ->add('image')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Projectsemma::class,
        ]);
    }
}

src/Controller/ApiController.php
<?php

namespace App\Controller;

use App\Entity\Projectsemma;
use App\Form\ProjectsemmaType;
use App\Repository\ProjectsemmaRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/apiprojectsemma')]
class ApiController extends AbstractController
{
    #[Route('/list', name: 'app_apiprojectsemma_index', methods: ['GET'])]
    public function index(ProjectsemmaRepository $projectsemmaRepository): Response
    {
        $projectsemma = $projectsemmaRepository->findAll();

        $data = [];

        foreach ($projectsemma as $p) {
            $data[] = [
                'id' => $p->getId(),
                'project_name' => $p->getProjectName(),
                'date' => $p->getDate(),
                'used_technology' => $p->getUsedTechnology(),
                'image' => $p->getImage(),
            ];
        }
        //dump($data);die; 
        //return $this->json($data);
        return $this->json($data, $status = 200, $headers = ['Access-Control-Allow-Origin'=>'*']);
    }
}

src/Controller/ProjectsemmaController.php
<?php

namespace App\Controller;

use App\Entity\Projectsemma;
use App\Form\ProjectsemmaType;
use App\Repository\ProjectsemmaRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/projectsemma')]
class ProjectsemmaController extends AbstractController
{
    #[Route('/', name: 'app_projectsemma_index', methods: ['GET'])]
    public function index(ProjectsemmaRepository $projectsemmaRepository): Response
    {
        return $this->render('projectsemma/index.html.twig', [
            'projectsemmas' => $projectsemmaRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_projectsemma_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ProjectsemmaRepository $projectsemmaRepository): Response
    {
        $projectsemma = new Projectsemma();
        $form = $this->createForm(ProjectsemmaType::class, $projectsemma);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $projectsemmaRepository->save($projectsemma, true);

            return $this->redirectToRoute('app_projectsemma_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('projectsemma/new.html.twig', [
            'projectsemma' => $projectsemma,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_projectsemma_show', methods: ['GET'])]
    public function show(Projectsemma $projectsemma): Response
    {
        return $this->render('projectsemma/show.html.twig', [
            'projectsemma' => $projectsemma,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_projectsemma_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Projectsemma $projectsemma, ProjectsemmaRepository $projectsemmaRepository): Response
    {
        $form = $this->createForm(ProjectsemmaType::class, $projectsemma);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $projectsemmaRepository->save($projectsemma, true);

            return $this->redirectToRoute('app_projectsemma_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('projectsemma/edit.html.twig', [
            'projectsemma' => $projectsemma,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_projectsemma_delete', methods: ['POST'])]
    public function delete(Request $request, Projectsemma $projectsemma, ProjectsemmaRepository $projectsemmaRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$projectsemma->getId(), $request->request->get('_token'))) {
            $projectsemmaRepository->remove($projectsemma, true);
        }

        return $this->redirectToRoute('app_projectsemma_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/projectsemma/_delete_form.html.twig
<form method="post" action="{{ path('app_projectsemma_delete', {'id': projectsemma.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ projectsemma.id) }}">
    <button class="btn">Delete</button>
</form>

templates/projectsemma/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/projectsemma/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Projectsemma{% endblock %}

{% block body %}
    <h1>Edit Projectsemma</h1>

    {{ include('projectsemma/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_projectsemma_index') }}">back to list</a>

    {{ include('projectsemma/_delete_form.html.twig') }}
{% endblock %}

templates/projectsemma/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Projectsemma index{% endblock %}

{% block body %}
    <h1>Projectsemma index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Project_name</th>
                <th>Date</th>
                <th>Used_technology</th>
                <th>Image</th>
            </tr>
        </thead>
        <tbody>
        {% for projectsemma in projectsemmas %}
            <tr>
                <td>{{ projectsemma.id }}</td>
                <td>{{ projectsemma.projectName }}</td>
                <td>{{ projectsemma.date ? projectsemma.date|date('M-y') : '' }}</td>
                <td>{{ projectsemma.usedTechnology }}</td>
                <td>{{ projectsemma.image }}</td>
                <td>
                    <a href="{{ path('app_projectsemma_show', {'id': projectsemma.id}) }}">show</a>
                    <a href="{{ path('app_projectsemma_edit', {'id': projectsemma.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_projectsemma_new') }}">Create new</a>
{% endblock %}

templates/projectsemma/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Projectsemma{% endblock %}

{% block body %}
    <h1>Create new Projectsemma</h1>

    {{ include('projectsemma/_form.html.twig') }}

    <a href="{{ path('app_projectsemma_index') }}">back to list</a>
{% endblock %}

templates/projectsemma/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Projectsemma{% endblock %}

{% block body %}
    <h1>Projectsemma</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ projectsemma.id }}</td>
            </tr>
            <tr>
                <th>Project_name</th>
                <td>{{ projectsemma.projectName }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ projectsemma.date ? projectsemma.date|date('M-y') : '' }}</td>
            </tr>
            <tr>
                <th>Used_technology</th>
                <td>{{ projectsemma.usedTechnology }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_projectsemma_index') }}">back to list</a>

    <a href="{{ path('app_projectsemma_edit', {'id': projectsemma.id}) }}">edit</a>

    {{ include('projectsemma/_delete_form.html.twig') }}
{% endblock %}